[versions]
# JDK version for toolchain
jdk = "{{ @@03|(11|17|21|25)|JDK version=25@@jdk_version }}"
# https://kotlinlang.org/
kotlin = "{{ kotlin_version }}"
# https://mvnrepository.com/artifact/com.gradleup.shadow/shadow-gradle-plugin
shadow = "9.0.0"
# https://ajalt.github.io/clikt/
clikt = "5.0.3"
# https://ajalt.github.io/mordant/
mordant = "3.0.2"
# https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
junit = "5.12.2"
# https://mvnrepository.com/artifact/org.assertj/assertj-core
assertj = "3.27.3"
# https://mvnrepository.com/artifact/io.mockk/mockk
mockk = "1.14.2"

[libraries]
# Clikt without JNA (no native access warnings on JDK 21+)
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
mordant-core = { module = "com.github.ajalt.mordant:mordant-core", version.ref = "mordant" }
mordant-markdown = { module = "com.github.ajalt.mordant:mordant-markdown", version.ref = "mordant" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
