[versions]
jdk = "{{ @@03|(11|17|21)|JDK version=21@@jdk_version }}"
kotlin = "{{ kotlin_version }}"
shadow = "9.3.1"
clikt = "5.1.0"
junit = "5.10.1"
assertj = "3.24.2"
mockk = "1.13.8"

[libraries]
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
clikt-markdown = { module = "com.github.ajalt.clikt:clikt-markdown", version.ref = "clikt" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
