[versions]
# JDK version for toolchain
jdk = "{{ @@03|(11|17|21|25)|JDK version=25@@jdk_version }}"
# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib
kotlin = "{{ kotlin_version }}"
# https://mvnrepository.com/artifact/com.gradleup.shadow/shadow-gradle-plugin
shadow = "9.0.0"
# https://mvnrepository.com/artifact/io.ktor/ktor-server-core-jvm
ktor = "3.1.0"
# https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
logback = "1.5.18"
# https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
junit = "5.12.2"
# https://mvnrepository.com/artifact/org.assertj/assertj-core
assertj = "3.27.3"
# https://mvnrepository.com/artifact/io.mockk/mockk
mockk = "1.14.2"

[libraries]
ktor-server-core-jvm = { module = "io.ktor:ktor-server-core-jvm" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty" }
ktor-server-core = { module = "io.ktor:ktor-server-core" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
