[versions]
jdk = "{{ @@03|(11|17|21)|JDK version=21@@jdk_version }}"
kotlin = "{{ kotlin_version }}"
shadow = "9.3.1"
junit = "5.10.1"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
